### ISSUE TITLE
Include a composer.json file.

### ISSUE THREAD

**Issue by cosmicdreams** [mlsamuelson/hax#3]
It appears that this module depends on the restui project.  Therefore a composer.json file should be included so that those who manage their dependencies via composer can automatically get that dependency. 

Also, if it really is a dependency the hax.info.yml should list it as one.

**Comment by mlsamuelson** [comment]
During development it was a dependency at one point, but I missed pulling it out somewhere when I determined it wasn't actually needed, because we could specify the allowed method in the hax.routing.yml file.

Ah - found it in the README.md: fixed.

https://github.com/mlsamuelson/hax/commit/778fcecaa83b9ffa40203f22e18882df1beb18b4

Thank you!

**Comment by mmenavas** [comment]
Here's a `composer.json` file that could be used in case a dependency, such as 'drupal/webcompenents', is added in the future.

```
{
  "name": "drupal/hax",
  "type": "drupal-module",
  "description": "A completely Headless Authoring eXperience, #haxtheweb.",
  "keywords": ["Drupal"],
  "license": "GPL-2.0+",
  "homepage": "https://www.drupal.org/project/hax",
  "minimum-stability": "dev",
  "support": {
    "issues": "https://www.drupal.org/project/issues/hax",
    "source": "http://cgit.drupalcode.org/hax"
  },
  "require": {}
}
```
